### PR TITLE
[systemd]: Mask systemd-networkd on non-smart-switch platforms

### LINKED ISSUE #24523: Bug: [Trixie] systemd-networkd.socket starts on non-smartswitch platforms
### Is it platform specific

generic

### Importance or Severity

Critical

### Description of the bug

systemd-networkd.socket isn't expected to start on non-smartswitch npu/dpu platforms. However we see it tries to start and we see following errors in syslog. 

```
ERR systemd[1]: Failed to listen on systemd-networkd.socket - Network Service Netlink Socket.
WARNING systemd[1]: systemd-networkd.socket: Failed with result 'service-start-limit-hit'.
```

### Steps to Reproduce

Install Debian 13 based sonic image on non-smartswitch platform

### Actual Behavior
systemd-networkd.socket tries to start on non-smartswitch platforms

### Expected Behavior
We shouldn't see any errors and ideally we shouldn't start systemd-networkd.socket on non-smartswitch platforms.

### Relevant log output

```shell
root@sonic:/home/admin# systemctl status systemd-networkd.socket
× systemd-networkd.socket - Network Service Netlink Socket
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.socket; disabled; preset: enabled)
     Active: failed (Result: service-start-limit-hit) since Thu 2025-11-13 23:33:18 UTC; 38s ago
   Duration: 1min 8.775s
 Invocation: 0fb94c68161a4024837ff54c92e7eb71
   Triggers: ● systemd-networkd.service
       Docs: man:systemd-networkd.service(8)
             man:rtnetlink(7)
     Listen: route 1361 (Netlink)

root@sonic:/home/admin# systemctl list-dependencies --reverse systemd-networkd.socket
systemd-networkd.socket
○ └─systemd-networkd.service
```

systemd-networkd.service doesn't start as expected on non-smartswitch platforms because of ExecCondition option. However we don't such such option for the socket

```
root@sonic:/home/admin# systemctl status systemd-networkd
○ systemd-networkd.service - Network Configuration
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; disabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/systemd-networkd.service.d
             └─override.conf
     Active: inactive (dead) (Result: exec-condition) since Thu 2025-11-13 23:33:18 UTC; 1min 30s ago
 Invocation: 207328a3ce1d4861a43b389d393f6d37
TriggeredBy: × systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
             man:org.freedesktop.network1(5)
    Process: 25127 ExecCondition=/bin/bash /usr/local/bin/is-npu-or-dpu.sh (code=exited, status=1/FAILURE)
   FD Store: 0 (limit: 512)
```

### LINKED ISSUE #25091: Bug: Cosmetic systemd [DEPEND] Dependency failed messages on warm-reboot
### Is it platform specific

generic

### Importance or Severity

Low

### Description of the bug

After a successful SONiC warm-reboot, the serial console prints repeated [DEPEND] Dependency failed for systemd-networkd-persistent-storage.service messages (~10 times).

Only visible on serial console.

The network stack, orchagent, and SONiC services start correctly.

This does not occur on cold reboot.

Impact: Cosmetic only — does not affect functionality.

Suggested action: 
Mask or suppress systemd-networkd-persistent-storage.service during warm-reboot

### Steps to Reproduce

Run AMD64 until SONiC fully up
Use SHELL in the SERIAL-CONSOLE
apply:   warm-reboot 
After successful reboot wait for some minutes for the prints (see log below).

### Actual Behavior and Expected Behavior

-

### Relevant log output

```shell
Sep 03 19:12:42 sonic systemd[1]: systemd-networkd-persistent-storage.service: Job systemd-networkd-persistent-storage.service/st
Sep 03 19:32:00 sonic systemd[1]: systemd-networkd-persistent-storage.service: Bound to unit systemd-networkd.service, but unit i 
Sep 03 19:32:00 sonic systemd[1]: Dependency failed for systemd-networkd-persistent-storage.service - Enable Persistent Storage i 
Sep 03 19:32:00 sonic systemd[1]: systemd-networkd-persistent-storage.service: Job systemd-networkd-persistent-storage.service/st 
Sep 03 20:20:58 sonic systemd[1]: systemd-networkd-persistent-storage.service: Bound to unit systemd-networkd.service, but unit i 
Sep 03 20:20:58 sonic systemd[1]: Dependency failed for systemd-networkd-persistent-storage.service - Enable Persistent Storage i 
Sep 03 20:20:58 sonic systemd[1]: systemd-networkd-persistent-storage.service: Job systemd-networkd-persistent-storage.service/st
...............
```

### Output of `show version`, `show techsupport`

```shell
-
```

### Attach files (if any)

-

### PR DESCRIPTION
**Pull request by Bojun-Feng**
#### Why I did it

Fix #25091
Fix #24523

After a successful SONiC warm-reboot, the serial console prints repeated `[DEPEND] Dependency failed for systemd-networkd-persistent-storage.service` and similar messages on non-smart-switch platforms. This is a cosmetic issue that does not affect functionality but is jarring for anyone monitoring startup output.

The root cause is that `systemd-networkd.service` uses an `ExecCondition` to skip execution on non-smart-switch platforms. However, its dependent services (`systemd-networkd-persistent-storage.service`, `systemd-networkd-wait-online.service`) still attempt to start and fail with dependency errors.

#### How I did it

* Added `mask_networkd_for_non_smart_switch()` function to systemd-sonic-generator that creates a symlink to `/dev/null` for `systemd-networkd.service` when not on smart-switch platforms (DPU/NPU)
* The masking occurs at early boot during generator execution, before systemd loads unit files
* Masking systemd-networkd directly causes all dependent services to be automatically skipped by systemd's dependency resolution
* Added `validate_masked_services()` test to verify correct masking behavior across all platform configurations

#### How to verify it

1. Build a SONiC image with this change
2. Boot on a non-smart-switch platform (no DPU/DPUS in platform.json)
3. Perform a warm-reboot: `warm-reboot`
4. Monitor serial console output
5. Verify no "Dependency failed for systemd-networkd-persistent-storage.service" or similar messages appear

#### Description for the changelog

Mask systemd-networkd.service on non-smart-switch platforms to prevent dependency failure

### CODE REVIEW

**Comment by Bojun-Feng** [comment]
Hi @cpackham-atlnz, can you check if this PR solves your issues? If we mask `systemd-networkd` this should skip all its dependencies and there should be no more error messages from any `networkd` related dependencies.

**Comment by cpackham-atlnz** [comment]
@Bojun-Feng yes that seems to do the trick

**Comment by Bojun-Feng** [comment]
Great! Opening this up for review

File: src/systemd-sonic-generator/systemd-sonic-generator.cpp [hunk 1]
```diff
@@ -1021,6 +1041,11 @@ int ssg_main(int argc, char **argv) {
         }
     }
 
+    // Mask systemd-networkd on non-smart-switch platforms
+    if (mask_networkd_for_non_smart_switch(install_dir) != 0) {
+        return -1;
+    }
```
Comment (saiarcot895) [inline src/systemd-sonic-generator/systemd-sonic-generator.cpp:1047]: This should probably be in the else-block of the above condition; otherwise, it'll apply for smart switch as well.

Comment (saiarcot895) [reply src/systemd-sonic-generator/systemd-sonic-generator.cpp:1047]: Oh, I just saw you have a `if (smart_switch)` in the function, that works.

**Review by saiarcot895 — APPROVED** [review]

**Comment by YatishSVC** [comment]
@vmittal-msft , @tjchadaga , I think we need this in 202511 branch as well
